apiVersion: v1
kind: Service
metadata:
  name: {{ template "jackett.fullname" . }}
  labels:
    app: {{ template "jackett.name" . }}
    chart: {{ template "jackett.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.name }}
      protocol: {{ .Values.service.protocol }}
      name: {{ .Values.service.name }}
  selector:
    app: {{ template "jackett.name" . }}
    release: {{ .Release.Name }}
